server {
    listen       80;
    server_name  localhost;

    root   /usr/share/nginx/html;
    index  index.html index.htm;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # Optional: increase file upload size and basic headers
    client_max_body_size 10M;
    sendfile on;
}
